language: php

cache:
  directories:
    - $HOME/.composer/cache/files
    - .phpunit

env:
  global:
    - SYMFONY_PHPUNIT_REMOVE="symfony/yaml" SYMFONY_PHPUNIT_DIR=".phpunit" SYMFONY_PHPUNIT_VERSION=6.0

branches:
    only: [master, stable]

matrix:
  fast_finish: true
  include:
    - php: nightly
      env: DEPS=dev

    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_PHPUNIT_VERSION=5.7 SYMFONY_DEPRECATIONS_HELPER=23

    - php: 7.1
      env: LTS_VERSION=2 SYMFONY_DEPRECATIONS_HELPER=23
    - php: 7.1
      env: LTS_VERSION=3

    - php: 7.1
      env: LTS_VERSION=4.*@dev SYMFONY_DEPRECATIONS_HELPER=1

  allow_failures:
    - php: nightly

before_install:
  - set -eo pipefail
  - phpenv config-rm xdebug.ini || true
  - if [ -n "$LTS_VERSION" ]; then composer require "symfony/lts:${LTS_VERSION}" --no-update; fi
  - if [ "$DEPS" != "" ]; then perl -pi -e "s/^}\$/,\"minimum-stability\":\"$DEPS\"}/" composer.json; fi

install: composer update --prefer-dist $COMPOSER_FLAGS

script: ./vendor/bin/simple-phpunit
